### PR TITLE
Null item array patch

### LINKED ISSUE #731: ArgumentNullException in Inventory.cs
Apparently sometimes the Items array is null?
>[Shaun The Sheep 2015-02-28 11:32:11] WARN: Unknown error occurred: System.ArgumentNullException: Argument cannot be null.
Parameter name: source
   in System.Linq.Enumerable.Where{TSource}(IEnumerable`1 source, Func`2 predicate)
   in SteamTrade.Inventory.GetItemsByDefindex(Int32 defindex) in X:\SteamBot-master\SteamTrade\Inventory.cs:line 79

Ideas?

### PR DESCRIPTION
**Pull request by bartico6**
Prevents a malformed server response from being processed - a empty 200 OK response happens randomly from time to time on all sorts of TF2 (and propably non-TF2 as well) inventories - this will fetch the inventory three times (if it's still null) before returning an object.
If it's not the perfect way to go - correct me, please. Exceptions raised while attempting to process a malformed inventory like one mentioned of course kills the trade instantly.
This somewhat fixes #731.

### CODE REVIEW

File: SteamTrade/Inventory.cs [hunk 1]
```diff
@@ -15,11 +15,17 @@ public class Inventory
...
         /// <param name="steamWeb">The SteamWeb instance for this Bot</param>
-        public static Inventory FetchInventory (ulong steamId, string apiKey, SteamWeb steamWeb)
+        public static Inventory FetchInventory(ulong steamId, string apiKey, SteamWeb steamWeb)
         {
-            var url = "http://api.steampowered.com/IEconItems_440/GetPlayerItems/v0001/?key=" + apiKey + "&steamid=" + steamId;
-            string response = steamWeb.Fetch (url, "GET", null, false);
-            InventoryResponse result = JsonConvert.DeserializeObject<InventoryResponse>(response);
+            int attempts = 1;
+            InventoryResponse result = null;
+            while ((result.result.items == null || result == null) && attempts <= 3)
```
Comment (WildCard65) [inline SteamTrade/Inventory.cs]: Y not make this configurable with default value of 3? Json.Net has an attribute called DefaultValueAttribute you can apply to specify a default value

**Comment by WildCard65** [comment]
Calling @BlueRaja to this for review.

**Comment by bartico6** [comment]
I kept forgetting to come here and close this PR because of the issue above.

**Comment by WildCard65** [comment]
You don't need to close issue when you can add more commits onto PR

**Comment by bartico6** [comment]
Fixed the mentioned bug with NPE's / NRE's appearing due to wrong order of nullchecks. Silly me.

**Comment by bartico6** [comment]
As for configurable attempt amount - I'd say three works for all cases but I'll look into it later, currently dealing with more annoying bugs of my own bot :G
